{% set name = "ag-grid" %}
{% set version = "17.1.1" %}
{% set sha256 = "bcd35fb1dcd0c1302b43fe95531b9df8d5a119430c202a8f49f5957a82b634b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ag-grid/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g ag-grid
  requires:
    - nodejs
   

about:
  home: https://github.com/ag-grid/ag-grid
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: 'Advanced Data Grid / Data Table supporting Javascript / React / AngularJS / Web Components'
  description: |
    Advanced Data Grid / Data Table supporting Javascript / React / AngularJS / Web Components 
  doc_url: https://www.ag-grid.com/
  dev_url: https://github.com/ag-grid/ag-grid

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
