{% set name = "ag-grid" %}
{% set version = "18.1.1" %}
{% set sha256 = "8da2eaef20643f02346d67a654225de9cfd47e2c48e2d6f4445721bc19e03bd4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ag-grid/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g ag-grid
  requires:
    - nodejs
   

about:
  home: https://github.com/ag-grid/ag-grid
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: 'Advanced Data Grid / Data Table supporting Javascript / React / AngularJS / Web Components'
  description: |
    Advanced Data Grid / Data Table supporting Javascript / React / AngularJS / Web Components 
  doc_url: https://www.ag-grid.com/
  dev_url: https://github.com/ag-grid/ag-grid

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
