travis:
  secure:
    BINSTAR_TOKEN: ibkGthxN25nxecIVINlIcu4LxipeH8WwzkwjWEfSRbUWt8kwnrpfiXli3mjd4lg4JNJ/Ui1PEyYkZUrevPLOFUxcqW+DH2Ihacc6XaB9KEM8AmbA+tfkguelpPgiikCnlUYsrZ4L0qmwsJAtN5+PFKNI9a6VAbl3Xd/QmDqSH/jbDO905ZQrbJ2t63crfjKSPK190fQSKp+lvo3KwSBF36su91uCEtQL9PI5ZQ51GuCzeUFodAgoAhzx+5e+w3Oi9QdSNpHSIecFH3fhTPtd+Cupx3I/TOkaPuHs1LslcJKEnZu7w3YP2yiExcmVpGu2P9ltLTrc3YvSPVXmRFvLZ+yiOpdRJXdm8wigpm7w/1EQzu0sbkyKopzAhLVcSxGI77BewMwhonoeTHN/muokjBRnH3MyD9Lin9205p7BbL+yKv28hDpxLwrk35N+fjevOfiONBomwLuMSPCM7qyvHuJlUyG58kkCAayFm/xaWfAEgxF8Ep1jUDm2jU08yGyzNcvry3jAOY+YvvbLQOfBNbCwGJVBPBL2/v66/uyOVrgbDmtwJVZLnxVPsIO4PCYamWeC4IVsulrOYWJg/N77bFFyYqxr+n3z/EtToYg/a3f4FqTlmODKwTqmvMk0IomSyemys0Q2Q84pJnJEwMMk6Whxfh8LWFJOU3HBiEih1po=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
