travis:
  secure:
    BINSTAR_TOKEN: u+RTaFDqyJu2Z0/5bsb/gecXkRqSwu31vDipTpFg3/a6zf+rHPgxjj+KwLSNzcYWEGZkvAKoEcVGd6OlWntS4s7iG9LQyA5+ugdBnoQi2eqo2oQFW5jOjbZsi69NcsOf2LGoGBBdsRd3ozfg1G7NHJJkVgp1y5K/uEOPY0FXd9Irk1gxI++/Tju+qDHrvamOv8TtX2IKKw0tZ6N9mBsvl8YThBuM6yxdPhrPA3I/7LErcRkWGR7Znqz/P9bjN5gyqwlOLrt+iAGM5zblSc5NBFEYVtCsNcE1Eww9/ewHtsGyC8Okx5RBabsHBAe4dmPBQbtseH/7GxVx8RdsIuDLrKMcWFzTheZI7eD19VDdr+O1oRdGV1RpJPJYNgPA9tqy8EYEuLANdFiQNoTFEghsM51hGBE2dLAcCp5pKWko1JpCeGbDXsq9qO+76Yxu96+rFKCmPOaqWkavwCHWDxXZpyP8Gx7wsLJeohjrq/80cnGXFVpOdXOSTxixJBTVHOJd1haK1T6LBmSeiqAeJl1LOf+VKb17CtNcL8cc4Jzp4yAOcKntyeOmj4xnPBsLB5HDlFojaTsZkVxzEKJSiTbOQ/N9twMEmrzIohQnu6Z0X4OzRSEF1OxWdVcyII+PB250u091hlH9BbZ+A9Gl+69Z01ZMoBI96wk35mBZl5JD2MQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
